name: YWM Build Status

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libx11-dev libxft-dev libxext-dev libfreetype6-dev
      - name: Build
        run: |
          ./configure
          make

